feat: [tentative] ros2 bridge mode
Signed-off-by: kobayu858 <yutaro.kobayashi.2@tier4.jp>

diff --git a/scripts/e2e_test_1to1_with_ros2pub b/scripts/e2e_test_1to1_with_ros2pub
--- a/scripts/e2e_test_1to1_with_ros2pub
+++ b/scripts/e2e_test_1to1_with_ros2pub
@@ -71,8 +71,8 @@ else
     SUB_QOS_DEPTH=(1 10)
     SUB_TRANSIENT_LOCAL=(true false)
     USE_TAKE_SUB=(true false)
+    BRIDGE_FROM_ROS2=(true false)
 
-    # bridge_from_ros2 is always true, because false is agnocasst's default behavior.
     COUNT=0
     for launch_pub_before_sub in ${LAUNCH_PUB_BEFORE_SUB[@]}; do
         for pub_qos_depth in ${PUB_QOS_DEPTH[@]}; do
@@ -80,25 +80,28 @@ else
                 for sub_qos_depth in ${SUB_QOS_DEPTH[@]}; do
                     for sub_transient_local in ${SUB_TRANSIENT_LOCAL[@]}; do
                         for use_take_sub in ${USE_TAKE_SUB[@]}; do
-                            COUNT=$((COUNT + 1))
-                            sed -i "s/launch_pub_before_sub:.*/launch_pub_before_sub: $launch_pub_before_sub/g" $CONFIG_FILE
-                            sed -i "s/pub_qos_depth:.*/pub_qos_depth: $pub_qos_depth/g" $CONFIG_FILE
-                            sed -i "s/pub_transient_local:.*/pub_transient_local: $pub_transient_local/g" $CONFIG_FILE
-                            sed -i "s/sub_qos_depth:.*/sub_qos_depth: $sub_qos_depth/g" $CONFIG_FILE
-                            sed -i "s/sub_transient_local:.*/sub_transient_local: $sub_transient_local/g" $CONFIG_FILE
-                            sed -i "s/use_take_sub:.*/use_take_sub: $use_take_sub/g" $CONFIG_FILE
-                            echo "====================== $COUNT / 64 ======================" | sudo tee /dev/kmsg
-                            show_config
-                            launch_test ssrc/agnocast_e2e_test/test/test_1to1_with_ros2pub.py
+                            for bridge_from_ros2 in ${BRIDGE_FROM_ROS2[@]}; do
+                                COUNT=$((COUNT + 1))
+                                sed -i "s/launch_pub_before_sub:.*/launch_pub_before_sub: $launch_pub_before_sub/g" $CONFIG_FILE
+                                sed -i "s/pub_qos_depth:.*/pub_qos_depth: $pub_qos_depth/g" $CONFIG_FILE
+                                sed -i "s/pub_transient_local:.*/pub_transient_local: $pub_transient_local/g" $CONFIG_FILE
+                                sed -i "s/sub_qos_depth:.*/sub_qos_depth: $sub_qos_depth/g" $CONFIG_FILE
+                                sed -i "s/sub_transient_local:.*/sub_transient_local: $sub_transient_local/g" $CONFIG_FILE
+                                sed -i "s/use_take_sub:.*/use_take_sub: $use_take_sub/g" $CONFIG_FILE
+                                sed -i "s/bridge_from_ros2:.*/bridge_from_ros2: $bridge_from_ros2/g" $CONFIG_FILE
+                                echo "====================== $COUNT / 128 ======================" | sudo tee /dev/kmsg
+                                show_config
+                                launch_test src/agnocast_e2e_test/test/test_1to1_with_ros2pub.py
 
-                            if [ $? -ne 0 ]; then
-                                echo "Test failed." | sudo tee /dev/kmsg
-                                if [ "$CONTINUE_ON_FAILURE" = true ]; then
-                                    FAILURE_COUNT=$((FAILURE_COUNT + 1))
-                                else
-                                    exit 1
+                                if [ $? -ne 0 ]; then
+                                    echo "Test failed." | sudo tee /dev/kmsg
+                                    if [ "$CONTINUE_ON_FAILURE" = true ]; then
+                                        FAILURE_COUNT=$((FAILURE_COUNT + 1))
+                                    else
+                                        exit 1
+                                    fi
                                 fi
-                            fi
+                            done
                         done
                     done
                 done
